# Generated by Django 4.0.1 on 2022-01-08 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='liked_by_user',
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.ManyToManyField(related_name='comment_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
