# Generated by Django 3.2.9 on 2022-01-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_options_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.ImageField(default=models.ImageField(upload_to='photos/%Y/%m/%d/'), upload_to='previews/%Y/%m/%d/'),
        ),
    ]
